### ISSUE TITLE
Kubernetes

### ISSUE THREAD

**Issue by bhack** [RedisLabs/DockerHub#10]
Official [redis](https://github.com/kubernetes/charts/tree/master/stable/redis) and [redis-ha](https://github.com/kubernetes/charts/tree/master/stable/redis) charts are based on third party images.
Could be useful if these could rely on official redis docker images.

**Comment by cihanb** [comment]
@bhack , is this about ReJSON or kubernetes/charts images or both?

**Comment by bhack** [comment]
Basically about k8/charts but related also to ReJSON cause the "official" kubernetes/charts are all based on third party docker images.

**Comment by jlegrone** [comment]
@bhack this PR to `stable/redis` makes the chart compatible with `redislabs/rejson`: https://github.com/helm/charts/pull/7745

There is another PR that may do the same for `stable/redis-ha`: https://github.com/helm/charts/pull/7323

Will these changes help with your use case?

**Comment by bhack** [comment]
If we will reach some consensus there :wink: ..probably yes
